# Site settings
baseurl = "/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Computational Social Science"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-90951528-1"
hasCJKLanguage = false

[params]
	name = "Gokhan Ciflikli"
	description = "Computational Social Science, Data Science, Visualization, R, Python"
	bio = "R | Shiny Apps | Data Visualization | ML | Python"
	# Enter optionally your twitter account
	twitter = "gokhan_ciflikli"
	enableRSS = false

	# Disqus comment
	disqusShortname = "gokhancif"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = true

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""
  
  # share on twitter
  shareOnTwitter = true

  # share on facebook
  shareOnFacebook = true

# Add additional social link entries underneath
[social]
  github-square = "https://github.com/ciflikli"
