# Site settings
baseurl = "https://www.gokhan.io/"
canonifyurls = true
languageCode = "en"
title = "Gokhan Ciflikli, Ph.D."
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-90951528-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
paginate = 20

[outputFormats.MyEnrichedFormat]
protocol = "https://"

[params]
	name = "Gökhan Çiflikli, Ph.D."
	job = "Senior Data Scientist | Attest"
	description = "Data Science, Visualization, Machine Learning, R"
	bio = "[R](https://gokhan.io/categories/r) | [Data Visualization](https://gokhan.io/categories/visualization) | [Predictive Modeling](https://gokhan.io/categories/prediction)"

	github = "ciflikli"
	enableRSS = true
	
	title404 = "This is not the web page you are looking for."
	subtitle404 = "Perhaps your father wanted you to browse this page when you were old enough, but your uncle wouldn't allow it. He feared you might follow old Obi-Wan on some damn fool idealistic crusade like your father did..."

	disqusShortname = "gokhancif"
	enableDisqus = true

	enableGoogleAnalytics = true

	custom_css = []
	customJS  = []

	aboutAuthor = "Data Scientist and R Developer"

	iconFont = "font-awesome"
  
  shareOnTwitter = true

  shareOnFacebook = true

[social]

  github-square = "https://github.com/ciflikli"
  linkedin = "https://www.linkedin.com/in/gokhan-ciflikli/"
  twitter-square = "https://www.twitter.com/gokhan_ciflikli"
