# Site settings
baseurl = "https://www.gokhan.io/"
canonifyurls = false
languageCode = "en"
title = "Gokhan Ciflikli | Principal AI Engineer at Healf"
theme = "gokhan-noir"
googleAnalytics = "G-47S8FBKW4W"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]

[pagination]
  pagerSize = 20

[params]
  name = "Gökhan Çiflikli, PhD"
  job = "Principal AI Engineer at Healf"
  tagline = "Building Wellbeing Intelligence"
  description = "Data Science, Machine Learning, AI, Python, R"
  github = "ciflikli"
  enableRSS = true
  enableGoogleAnalytics = true

  title404 = "This is not the web page you are looking for."
  subtitle404 = "Perhaps your father wanted you to browse this page when you were old enough, but your uncle wouldn't allow it. He feared you might follow old Obi-Wan on some damn fool idealistic crusade like your father did..."

[params.social]
  linkedin = "https://www.linkedin.com/in/gokhan-ciflikli/"
  substack = "https://teamcraft.substack.com/"
  spotify = "https://open.spotify.com/album/5anGntZJaDDBog1XqiSDSj"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    lineNos = false
    style = "catppuccin-mocha"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/about/"
    weight = 3
